import HeightWeightScaleProtocol from './HeightWeightScaleProtocol';
import NormalBleScaleProtocol from './NormalBleScaleProtocol';
import OneToMultiBroadcastScaleProtocol from './OneToMultiBroadcastScaleProtocol';
import OneToOneBroadcastScaleProtocol from './OneToOneBroadcastScaleProtocol';
import WspDualScaleProtocol from './WspDualScaleProtocol';
import ShareCLScaleProtocol from './ShareCLScaleProtocol';
import ShareScaleProtocol from './ShareScaleProtocol';
import WspDualScaleMesProtocol from './WspDualScaleMesProtocol';
import SphygmomanometerProtocol from './SphygmomanometerProtocol';
import bleKitchenScaleProtocol from './kitchenScale/bleKitchenScaleProtocol';
import broadcastKitchenScaleProtocol from './kitchenScale/broadcastKitchenScaleProtocol';
declare const _default: {
    HeightWeightScaleProtocol: typeof HeightWeightScaleProtocol;
    NormalBleScaleProtocol: typeof NormalBleScaleProtocol;
    OneToMultiBroadcastScaleProtocol: typeof OneToMultiBroadcastScaleProtocol;
    OneToOneBroadcastScaleProtocol: typeof OneToOneBroadcastScaleProtocol;
    WspDualScaleProtocol: typeof WspDualScaleProtocol;
    ShareCLScaleProtocol: typeof ShareCLScaleProtocol;
    ShareScaleProtocol: typeof ShareScaleProtocol;
    WspDualScaleMesProtocol: typeof WspDualScaleMesProtocol;
    SphygmomanometerProtocol: typeof SphygmomanometerProtocol;
    bleKitchenScaleProtocol: typeof bleKitchenScaleProtocol;
    broadcastKitchenScaleProtocol: typeof broadcastKitchenScaleProtocol;
};
export default _default;
