import HeightWeightScaleProtocol from './HeightWeightScaleProtocol';
import NormalBleScaleProtocol from './NormalBleScaleProtocol';
import OneToMultiBroadcastScaleProtocol from './OneToMultiBroadcastScaleProtocol';
import OneToOneBroadcastScaleProtocol from './OneToOneBroadcastScaleProtocol';
import WspDualScaleProtocol from './WspDualScaleProtocol';
import ShareCLScaleProtocol from './ShareCLScaleProtocol';
import ShareScaleProtocol from './ShareScaleProtocol';
import SphygmomanometerProtocol from './SphygmomanometerProtocol';
import BleKitchenScaleProtocol from './kitchenScale/bleKitchenScaleProtocol';
import BroadcastKitchenScaleProtocol from './kitchenScale/broadcastKitchenScaleProtocol';
import FasciaGunMCUProtocol from './FasciaGunMCUProtocol';
import EightElectrodeScaleProtocol from './EightElectrodeScaleProtocol';
import WspDualScaleMesProtocol from './WspDualScaleMesProtocol';
import NormalBleScaleMesProtocol from './NormalBleScaleMesProtocol';
import ThermometerProtocol from './ThermometerProtocol';
declare const _default: {
    HeightWeightScaleProtocol: typeof HeightWeightScaleProtocol;
    NormalBleScaleProtocol: typeof NormalBleScaleProtocol;
    OneToMultiBroadcastScaleProtocol: typeof OneToMultiBroadcastScaleProtocol;
    OneToOneBroadcastScaleProtocol: typeof OneToOneBroadcastScaleProtocol;
    WspDualScaleProtocol: typeof WspDualScaleProtocol;
    ShareCLScaleProtocol: typeof ShareCLScaleProtocol;
    ShareScaleProtocol: typeof ShareScaleProtocol;
    WspDualScaleMesProtocol: typeof WspDualScaleMesProtocol;
    SphygmomanometerProtocol: typeof SphygmomanometerProtocol;
    ThermometerProtocol: typeof ThermometerProtocol;
    BleKitchenScaleProtocol: typeof BleKitchenScaleProtocol;
    BroadcastKitchenScaleProtocol: typeof BroadcastKitchenScaleProtocol;
    FasciaGunMCUProtocol: typeof FasciaGunMCUProtocol;
    NormalBleScaleMesProtocol: typeof NormalBleScaleMesProtocol;
    EightElectrodeScaleProtocol: typeof EightElectrodeScaleProtocol;
};
export default _default;
